
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_exam_development

test:
  <<: *default
  database: blog_exam_test

production:
  <<: *default
  database: blog_exam_production
  username: blog_exam
  password: <%= ENV['BLOG_EXAM_DATABASE_PASSWORD'] %>
